# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2016-05-10 12:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampsModifie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomchamp', models.CharField(max_length=50)),
                ('valchamp', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datemodif', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('typetable', models.CharField(max_length=200, null=True)),
                ('typemod', models.IntegerField(choices=[(0, 'Ajout'), (1, 'Modifier'), (2, 'Supprimer'), (0, 'mod statut inconnu')], default=0)),
                ('ipmod', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(4, 'Statut Inconnu'), (1, 'SALLE'), (2, 'personne'), (3, 'groupe'), (4, 'uv'), (5, 'module'), (6, 'cour'), (7, 'type de cour'), (8, 'notes')], default=4)),
                ('typeG', models.IntegerField(choices=[(0, 'ajout'), (1, 'modifier'), (2, 'suprilmer')], default=0)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 176354, tzinfo=utc))),
                ('isvisible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaternModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 174354, tzinfo=utc))),
                ('semaineMin', models.IntegerField()),
                ('semaineMax', models.IntegerField()),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mecredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0)),
                ('hmin', models.IntegerField()),
                ('hmax', models.IntegerField()),
                ('isvisible', models.BooleanField(default=True)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('nom', models.CharField(max_length=30)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 155722, tzinfo=utc))),
                ('isvisible', models.BooleanField(default=True)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='horaireProf',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('jdelaSemaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mecredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0)),
                ('hminMatin', models.IntegerField()),
                ('hmaxMatin', models.IntegerField()),
                ('hminApresMidi', models.IntegerField()),
                ('hmaxApresMidi', models.IntegerField()),
                ('isvisible', models.BooleanField(default=True)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('nom', models.CharField(max_length=30)),
                ('isvisible', models.BooleanField(default=True)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('lanote', models.IntegerField(blank=True, default=0, null=True)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 155722, tzinfo=utc))),
                ('isvisible', models.BooleanField(default=True)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('sexe', models.IntegerField(choices=[(0, 'Sexe Inconnu'), (1, 'Homme'), (2, 'Femme')], default=0)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('promotion', models.IntegerField(null=True)),
                ('type', models.IntegerField(choices=[(4, 'Statut Inconnu'), (0, 'Prof/Chercheur'), (1, 'Eleve'), (2, 'Administration'), (3, 'Administrateur Du Site')], default=4)),
                ('dateDeNaissance', models.DateField(null=True)),
                ('lieuDeNaissance', models.CharField(max_length=200, null=True)),
                ('numeroDeTel', models.CharField(max_length=40, null=True)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 155722, tzinfo=utc))),
                ('filter', models.CharField(max_length=200)),
                ('isvisible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('nom', models.CharField(max_length=30)),
                ('capacite', models.IntegerField(null=True)),
                ('type', models.IntegerField(choices=[(0, 'Type inconnu'), (1, 'Classe'), (2, 'Labo'), (3, 'Info')], default=0)),
                ('isvisible', models.BooleanField(default=True)),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='TypeCour',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('nom', models.CharField(max_length=30)),
                ('isExam', models.BooleanField()),
                ('isvisible', models.BooleanField(default=True)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 171853, tzinfo=utc))),
                ('groupe', models.ManyToManyField(blank=True, to='BDD.Groupe')),
                ('profs', models.ManyToManyField(blank=True, to='BDD.Personne')),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.CreateModel(
            name='UV',
            fields=[
                ('paternmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BDD.PaternModel')),
                ('nom', models.CharField(max_length=30)),
                ('isvisible', models.BooleanField(default=True)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime(2016, 5, 10, 12, 13, 26, 155722, tzinfo=utc))),
            ],
            bases=('BDD.paternmodel',),
        ),
        migrations.AddField(
            model_name='champsmodifie',
            name='champs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Modification'),
        ),
        migrations.AddField(
            model_name='note',
            name='personnenote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Personne'),
        ),
        migrations.AddField(
            model_name='note',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ANoter', to='BDD.Personne'),
        ),
        migrations.AddField(
            model_name='note',
            name='themodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Module'),
        ),
        migrations.AddField(
            model_name='news',
            name='personne',
            field=models.ManyToManyField(to='BDD.Personne'),
        ),
        migrations.AddField(
            model_name='module',
            name='theuv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.UV'),
        ),
        migrations.AddField(
            model_name='horaireprof',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Personne'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='modules',
            field=models.ManyToManyField(blank=True, to='BDD.Module'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='personnes',
            field=models.ManyToManyField(blank=True, to='BDD.Personne'),
        ),
        migrations.AddField(
            model_name='cour',
            name='salles',
            field=models.ManyToManyField(blank=True, to='BDD.Salle'),
        ),
        migrations.AddField(
            model_name='cour',
            name='typeCour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.TypeCour'),
        ),
    ]
