# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0002_auto_20160308_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 10, 34, 20, 756533)),
        ),
        migrations.AlterField(
            model_name='news',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 10, 34, 20, 764538)),
        ),
        migrations.AlterField(
            model_name='uv',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 10, 34, 20, 758534)),
        ),
    ]
